apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/

namespace: lab-workshop-3-w01-s001-prod
namePrefix: prod-

patchesStrategicMerge:
  - patch-env.yaml
commonLabels:
  env: prod
replicas:
  - name: cat-service
    count: 2
