apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: cat-service
  name: cat-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cat-service
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: cat-service
    spec:
      containers:
      - image: lab-workshop-3-w01-s001-registry.s1tour-prod-new-25cca0b.tanzu-labs.esp.vmware.com/cat-service:0.0.1-SNAPSHOT
        name: cat-service
        resources: {}
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        lifecycle:
          preStop:
            exec:
              command: [ "sh", "-c", "sleep 10" ]
        volumeMounts:
        - name: config-volume
          mountPath: /workspace/config
        env:
        - name: SPRING_CONFIG_LOCATION
          value: optional:classpath:/,optional:classpath:/config/,optional:file:./,optional:file:./config/
        - name: SPRING_MAIN_CLOUD_PLATFORM
          value: kubernetes
      volumes:
      - name: config-volume
        configMap:
          name: cat-service-config
status: {}
