apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

configMapGenerator:
  - name: cat-service-config
    files:
      - application.properties

images:
  - name: lab-workshop-3-w01-s001-registry.s1tour-prod-new-25cca0b.tanzu-labs.esp.vmware.com/cat-service # used for Kustomize matching
    newTag: latest
