apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd-image-updater.argoproj.io/image-list: cat-service-image=lab-workshop-3-w01-s001-registry.s1tour-prod-new-25cca0b.tanzu-labs.esp.vmware.com/cat-service
    argocd-image-updater.argoproj.io/cat-service-image.update-strategy: latest
    argocd-image-updater.argoproj.io/cat-service-image.allow-tags: regexp:^b\d*\.\d{8}\.\d{6}$
#    argocd-image-updater.argoproj.io/cat-service-image.ignore-tags: *
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/gitcred
  name: prod-cat-service
  
spec:
  destination:
    namespace: lab-workshop-3-w01-s001-prod
    server: https://kubernetes.default.svc
  project: default
  source:
    path: manifests/overlays/prod
    repoURL: https://github.com/djschny/cat-service-release-ops.git
    targetRevision: main
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    #    automated: {}
    automated:
      prune: true
