apiVersion: kpack.io/v1alpha1
kind: Builder
metadata:
  name: booternetes-builder
  
spec:
  tag: lab-workshop-3-w01-s001-registry.s1tour-prod-new-25cca0b.tanzu-labs.esp.vmware.com/booternetes-builder
  serviceAccount: default
  stack:
    name: lab-workshop-3-w01-stack
    kind: ClusterStack
  store:
    name: lab-workshop-3-w01-store
    kind: ClusterStore
  order:
    - group:
        - id: paketo-buildpacks/java
    - group:
        - id: paketo-buildpacks/nodejs
