apiVersion: kpack.io/v1alpha1
kind: ClusterStack
metadata:
  name: lab-workshop-3-w01-stack
spec:
  id: "io.buildpacks.stacks.bionic"
  buildImage:
    image: "paketobuildpacks/build:base-cnb"
  runImage:
    image: "paketobuildpacks/run:base-cnb"
